/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.canvasstudio;

import javax.imageio.IIOException;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.Test;

public class App {

	@Test
	public void tc01() throws Exception {

		System.setProperty("webdriver.chrome.driver", "C:\\ui-test\\GridConfig\\chromedriver.exe");  
		WebDriver driver=new ChromeDriver();
		int width = 600;
		int height = 500;

		try {
			
			driver.navigate().to("http://www.htmlcanvasstudio.com/");  
			driver.manage().window().maximize();

			WebElement drawLine = driver.findElement(By.cssSelector("input[class='button line']"));
			WebDriverWait wait = new WebDriverWait(driver, 5);
			wait.until(ExpectedConditions.elementToBeClickable(drawLine));
			drawLine.click();

			WebElement canvas = driver.findElement(By.cssSelector("#imageView"));
			Actions builder = new Actions(driver);
			builder.moveToElement(canvas, width/2-100, height/2).click();
			builder.release();
			builder.moveByOffset(200, 0).click();
			builder.build().perform();
			builder.moveToElement(canvas, width/2, height/2-100).click();
			builder.release();
			builder.moveByOffset(0, 200).click();
			builder.build().perform();

			WebElement rectangle = driver.findElement(By.cssSelector("input[class='button rectangle']"));
			rectangle.click();
			builder.moveToElement(canvas, 202, 394).click();
			builder.release();
			builder.moveByOffset(274, 65).click();
			builder.build().perform();

			WebElement eraser = driver.findElement(By.cssSelector("input[class='button eraser']"));
			eraser.click();

			builder.moveToElement(canvas, width/2-101, height/2).clickAndHold();
			builder.moveByOffset(200, 0).release();
			builder.build().perform();

		} catch (Exception e) {
			System.out.println(e);
			throw new Exception("Something went wrong");
		} finally {
			driver.quit();
		}
	}
}
